-- ============================================
-- CarMaint Pro — Supabase Database Setup (Legacy)
-- ============================================
-- ⚠️ هذا الملف قديم ومتعارض مع supabase-tables.sql
-- ⚠️ يرجى استخدام supabase-tables.sql بدلاً منه
-- ⚠️ This file is LEGACY. Use supabase-tables.sql instead.
-- ============================================
-- The main schema uses "users" table (TEXT id) while this file
-- used "profiles" table (UUID id). The codebase is built for "users".
-- If your database already has "profiles", you need to migrate.
-- ============================================
